services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: investpro-postgres-dev
    environment:
      POSTGRES_USER: investpro
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: brokerage
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - investpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U investpro -d brokerage"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: investpro-redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - investpro-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Backend API (Development Mode)
  backend:
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: investpro-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://investpro:secure_password_123@postgres:5432/brokerage
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - '5001:5000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - investpro-network
    restart: unless-stopped
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
      - ./apps/backend/logs:/app/logs

  # Frontend Web App (Development Mode)
  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    container_name: investpro-frontend-dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5001/api/v1
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - investpro-network
    restart: unless-stopped
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  investpro-network:
    driver: bridge
