name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build --workspace=apps/web

      - name: Lint web app
        run: npm run lint --workspace=apps/web

      - name: Test backend
        run: echo "No backend tests yet"
