version: '3.8'
services:
  web:
    build: ../web
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mobile:
    build: ../mobile
    # Mobile apps are typically built separately, placeholder for CI/CD
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/brokerage
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brokerage
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
